[build-system]
requires = ["setuptools-cuda", "setuptools", "wheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "thrustcu"
version = "0.0.1"

dependencies = ["pytest", "numpy"]
