[build-system]
requires = ["setuptools-cuda @ file:///home/dexter/Projects/setuptools-cuda/", "setuptools", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "example"
version = "0.0.1"




