name: build-and-test
on: [push]
jobs:
  run_tests:
    runs-on: [self-hosted,gpu]
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
      - name: build_and_run_examples
        run: |
          cd examples/01_basic
          pip install .
          pip install pytest-cov
          pytest --cov=setuptools_cuda --cov-report=xml
          cd ../02_thrust
          pip install .
          pip install pytest-cov
          pytest --cov=setuptools_cuda --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
