name: Testing examples
on: [pull_request]
jobs:
  run_tests:
    runs-on: [self-hosted,gpu]
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
      - name: build_and_run_examples
        run: |
          pip install .
          pip install -U setuptools cython wheel numpy
          cd examples/01_basic
          pip install --no-build-isolation .          
          pytest
          cd ../02_thrust
          pip install --no-build-isolation .        
          pytest
