name: Run tests and other quality checks

on: [pull_request]

jobs:
  run_quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/checkout@v3
      - name: Install dependencies and the package
        run: |
            python -m pip install --upgrade pip
            pip install .[test]
            pip install pre-commit
            pre-commit install
            pre-commit run -a
